C#/PortfolioFull/Portfolio/Models/CharacterRegistrationModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Portfolio.RealTimeBackend;

namespace Portfolio.Models
{
    public class CharacterRegistrationModel
    {
        //Checks for requirement done in characterregistration.js
        public Enums.Class Class { get; set; }

        public Enums.Role Role { get; set; }

        public int Level { get; set; }

        public Enums.Faction Faction { get; set; }

        public string Name { get; set; }
    }
}

C#/PortfolioFull/Portfolio/Models/ErrorViewModel.cs
using System;

namespace Portfolio.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

C#/PortfolioFull/Portfolio/Controllers/GroupFinderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Portfolio.Hubs;

namespace Portfolio.Controllers
{
    public class GroupFinderController : Controller
    {
        private readonly IHubContext<CharacterRegistrationHub> HubContext;
        public GroupFinderController(IHubContext<CharacterRegistrationHub> hubContext)
        {
            HubContext = hubContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Magtheridon()
        {
            return View();
        }

        public IActionResult Sargeras()
        {
            return View();
        }

        public IActionResult Area52()
        {
            return View();
        }

        //https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2
        public ActionResult Register(Portfolio.Models.CharacterRegistrationModel model)
        {
            if (ModelState.IsValid)
            {
                //TODO: Register user in backend
                
            }
            return View("Area52", model);
        }
    }
}

C#/PortfolioFull/Portfolio/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Portfolio.Models;

namespace Portfolio.Controllers
{
    public class HomeController : Controller
    {
        [Route("")]
        [Route("Home")]
        [Route("Index")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("Home/About")]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        [Route("Home/Contact")]
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        [Route("Home/Privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        [Route("Home/Test")]
        public IActionResult Test()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

C#/PortfolioFull/Portfolio/Controllers/WebToolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio.Controllers
{
    public class WebToolsController : Controller
    {
        [Route("WebTools")]
        [Route("WebTools/Index")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("WebTools/Calculator")]
        public IActionResult Calculator()
        {
            return View();
        }

        [Route("WebTools/ReadFast")]
        public IActionResult ReadFast()
        {
            return View();
        }

        [Route("WebTools/RecursiveTree")]
        public IActionResult RecursiveTree()
        {
            return View();
        }

        [Route("WebTools/FlockingSimulation")]
        public IActionResult FlockingSimulation()
        {
            return View();
        }

        [Route("WebTools/SecurityCams")]
        public IActionResult SecurityCams()
        {
            return View();
        }
    }
}

C#/PortfolioFull/Portfolio/Views/GroupFinder/Area52.cshtml
@model CharacterRegistrationModel
@using Portfolio.RealTimeBackend;
@{
    ViewData["Title"] = "Area 52";
    Layout = "~/Views/Shared/_GroupFinderLayout.cshtml";
}


    <div id="RegistrationInputFields">
        @Html.DropDownListFor(t => t.Class, new SelectList(Enum.GetValues(typeof(Enums.Class))), "Class")
        @Html.DropDownListFor(t => t.Role, new SelectList(Enum.GetValues(typeof(Enums.Role))), "Role")
        @Html.DropDownListFor(t => t.Level, new SelectList(Enumerable.Range(15, 46).Reverse()), "Level"))
        @Html.DropDownListFor(t => t.Faction, new SelectList(Enum.GetValues(typeof(Enums.Faction))), "Faction")
        @Html.TextBoxFor(t => t.Name, "Name")
        <button id="registerButton" type="submit">Register</button>
    </div>

<p id="classVerification" style="color: red; display:none"> Class is required</p>
<p id="roleVerification" style="color: red; display:none"> Role is required</p>
<p id="levelVerification" style="color: red; display:none"> Level is required</p>
<p id="factionVerification" style="color: red; display:none"> Faction is required</p>
<p id="nameVerification" style="color: red; display:none"> Name is required</p>

<div id="Status">
    <p>Tanks in queue: @ClientManager.TankCount</p>
    <p>Healers in queue: @ClientManager.HealerCount</p>
    <p>DPS in queue: @ClientManager.DamageCount</p>
</div>

<script src="~/lib/signalr/dist/browser/signalr.js"></script>
<script src="~/js/CharacterRegistration.js"></script>

C#/PortfolioFull/Portfolio/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

C#/PortfolioFull/Portfolio/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

C#/PortfolioFull/Portfolio/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

C#/PortfolioFull/Portfolio/Views/Home/Test.cshtml
@{
    ViewData["Title"] = "Test Page";
}
<h2>@ViewData["Title"]</h2>

<p>This is a test</p>

C#/PortfolioFull/Portfolio/Views/Shared/_GroupFinderLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Group Finder</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/groupfinder.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/groupfinder.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    </environment>
</head>
<body>
    @{
        string page = $"{ViewContext.RouteData.Values["action"]}".ToLowerInvariant();
    }
    <div class="sidebar">
        <h2 style="color: white;"><i class="fa fa-user-circle" style="padding-left: 7px; color: white;"></i> G-Finder</h2>
        <a asp-area="" asp-controller="GroupFinder" asp-action="Index" class="@(page == "index" ? "active" : "")">Home</a>
        <a asp-area="" asp-controller="GroupFinder" asp-action="Area52" class="@(page == "area52" ? "active" : "")">Area 52</a>
        <a asp-area="" asp-controller="GroupFinder" asp-action="Magtheridon" class="@(page == "magtheridon" ? "active" : "")">Magtheridon</a>
        <a asp-area="" asp-controller="GroupFinder" asp-action="Sargeras" class="@(page == "sargeras" ? "active" : "")">Sargeras</a>
    </div>
    <!--<partial name="_CookieConsentPartial" />-->

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="container">
                <p>&copy; 2019 - Ryan Darras</p>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

C#/PortfolioFull/Portfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portfolio</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Portfolio</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Test">Test Page</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Portfolio</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

C#/PortfolioFull/Portfolio/Views/Shared/_WebToolsLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web Tools</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/webtools.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/webtools.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    </environment>
</head>
<body>
    @{
        string page = $"{ViewContext.RouteData.Values["action"]}".ToLowerInvariant();
    }
    <div class="sidebar">
        <h2><i class="fa fa-user-circle" style="padding-left: 7px;"></i> Dashboard</h2>
        <a asp-area="" asp-controller="WebTools" asp-action="Index" class="@(page == "index" ? "active" : "")">Home</a>
        <a asp-area="" asp-controller="WebTools" asp-action="Calculator" class="@(page == "calculator" ? "active" : "")">Calculator</a>
        <a asp-area="" asp-controller="WebTools" asp-action="ReadFast" class="@(page == "readfast" ? "active" : "")">Read Fast</a>
        <a asp-area="" asp-controller="WebTools" asp-action="RecursiveTree" class="@(page == "recursivetree" ? "active" : "")">Recursive Tree</a>
        <a asp-area="" asp-controller="WebTools" asp-action="FlockingSimulation" class="@(page == "flockingsimulation" ? "active" : "")">Flocking Simulation</a>
        <a asp-area="" asp-controller="WebTools" asp-action="SecurityCams" class="@(page == "securitycams" ? "active" : "")">Security Cams</a>
    </div>
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="container">
                <p>&copy; 2019 - Portfolio</p>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

C#/PortfolioFull/Portfolio/Views/WebTools/Index.cshtml
@{
    ViewData["Title"] = "Web Tools";
    Layout = "~/Views/Shared/_WebToolsLayout.cshtml";
}

<h2>This is the home page</h2>
<p>This site will likely (not really, I'm lazy) get turned into a collection of projects that will be useful in various situations.</p>

<p>Eventual goals are to:</p>
<ul>
    <li>Home Automation - Security Cameras</li>
    <li>Home Automation - Lights</li>
    <li>Server - Remote Control Panel</li>
    <li>etc</li>
</ul>

<h2>About</h2>
<p>Hi, my name is Ryan. I do programming.</p>

C#/PortfolioFull/Portfolio/Views/WebTools/ReadFast.cshtml
@{
    ViewData["Title"] = "Read Fast";
    Layout = "~/Views/Shared/_WebToolsLayout.cshtml";
}

<style>
    .textElement {
        margin-top: 15px;
        width: 50%;
        border: 3px solid #888888;
        padding: 0px;
        padding-top: 10px;
        text-align: center;
        background-color: #000000;
        color: #ffffff;
    }

    .sliderElement {
        width: 50%;
        padding: 0px;
        padding-top: 5px;
        text-align: center;
        position: relative;
    }

    .textBoxElement {
        top: -10px;
        left: 50%;
        width: 50%;
    }


    /* The slider itself */
    .slider {
        -webkit-appearance: none; /* Override default CSS styles */
        width: 100%; /* Full-width */
        margin: 0px;
        height: 25px; /* Specified height */
        background: #d3d3d3; /* Grey background */
        outline: none; /* Remove outline */
        opacity: 0.7; /* Set transparency (for mouse-over effects on hover) */
        -webkit-transition: .2s; /* 0.2 seconds transition on hover */
        transition: opacity .2s;
    }

    /* Mouse-over effects */
    .slider:hover {
        opacity: 1; /* Fully shown on mouse-over */
    }

    /* The slider handle (use -webkit- (Chrome, Opera, Safari, Edge) and -moz- (Firefox) to override default look) */
    .slider::-webkit-slider-thumb {
        -webkit-appearance: none; /* Override default look */
        width: 25px; /* Set a specific slider handle width */
        height: 25px; /* Slider handle height */
        background: #000000; /* Green background */
        cursor: pointer; /* Cursor on hover */
    }
</style>

<div>
    <div class="textElement">
        <p id="textElement">A</p>
    </div>

    <div class="sliderElement">
        <input type="range" min="1" max="1000" value="200" class="slider" id="rangeSlider" onmousemove="UpdateSliderValue()">
        <div class="textcenter">
            <p id="sliderValue">200</p>
        </div>
    </div>

    <div class="textBoxElement">
        <textarea style="width:100%" id="textArea" rows="4" cols="75" oninput="Run()"></textarea>
    </div>
</div>



<script type="text/javascript">
    var myVar = null;
    var speed = 200;
    var str = "The average person reads roughly 200 to 250 words per minute. However by removing the necessity of having to move your eyes you will find out that you can read much faster. Try pasting your own text into the box below to try to read different things at different paces. The slider will take you from 1 word per minute to 1000 words per minute. See how fast you can go.";
    var split = str.split(" ");
    var index = 0;
    switchText();
    function switchText() {
        var text = split[index];
        index++;
        if (index == split.length) {
            index = 0;
        }
        document.getElementById("textElement").innerHTML = text;
        myVar = setTimeout(switchText, speed);
    }

    function Run() {
        if (!document.getElementById("textArea").value == "") {
            split = document.getElementById("textArea").value.split(" ");
            index = 0;
        }
        else {
            split = str.split(" ");
            index = 0;
        }


        clearTimeout(myVar);
        myVar = setTimeout(switchText, speed);
    }

    function UpdateSliderValue() {
        document.getElementById("sliderValue").innerHTML = document.getElementById("rangeSlider").value;
        speed = 60000 / document.getElementById("rangeSlider").value;
    }
</script>

C#/PortfolioFull/Portfolio/Views/WebTools/RecursiveTree.cshtml
@{
    ViewData["Title"] = "Recursive Tree";
    Layout = "~/Views/Shared/_WebToolsLayout.cshtml";
}

<style>
    .p5Canvas {
        display: block;
        margin:0;
        width:50%;
        position:relative;
    }
    input
    {
        width:400px !important;
        margin:0;
    }
    #p5holder
    {
        margin-top: 15px;
        left:0;
    }
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/addons/p5.dom.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/addons/p5.sound.min.js"></script>

<div id="p5holder">

</div>

<script>
    angle = 0;
    prevAngle = 0;
    function setup() {
        var canvas = createCanvas(400, 400);
        canvas.parent("p5holder");
        slider = createSlider(0, TWO_PI, PI / 4, 0.01);
        slider.parent("p5holder");
    }

    function draw() {
        angle = slider.value();
        if (angle != prevAngle) {
            background(51);
            stroke(255);
            translate(200, height);

            branch(100);
            prevAngle = angle;
        }

    }

    function branch(len) {
        line(0, 0, 0, -len);
        translate(0, -len);
        if (len > 4) {
            push();
            rotate(angle + ((Math.random() - .5) * 2 * angle));
            branch(len * ((Math.random() / 5) + .6));
            pop();
            push();
            rotate(-angle + ((Math.random() - .5) * 2 * angle));
            branch(len * ((Math.random() / 5) + .6));
            pop();
            if (len > 16) {
                push();
                rotate(((Math.random() - .5) * 2 * angle));
                branch(len * ((Math.random() / 5) + .6));
                pop();
            }
        }
    }

</script>